#!/usr/bin/env python3
"""Build VULGUS_Dictionary_v0.2.xlsx from vulgus_lexicon.json.

Reads the canonical JSON and produces a human-readable xlsx for review.
Requires openpyxl: pip install --user openpyxl
"""

from __future__ import annotations
import json, os, sys

try:
    import openpyxl
except ImportError:
    print('ERROR: openpyxl not installed. Run: pip install --user openpyxl')
    sys.exit(1)

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JSON_PATH = os.path.join(REPO, 'dictionary', 'vulgus_lexicon.json')
OUT_PATH  = os.path.join(REPO, 'dictionary', 'VULGUS_Dictionary_v0.2.xlsx')

# Column order and JSON key mapping
COLUMNS = [
    ('ID',              'id'),
    ('Word',            'word'),
    ('Variants',        'variants'),
    ('Severity',        'severity'),
    ('Region',          'region'),
    ('Era',             'era'),
    ('Semantic Type',   'semantic_type'),
    ('Tags',            'tags'),
    ('Etymology Note',  'etymology_note'),
    ('Definition',      'definition'),
    ('Part of Speech',  'part_of_speech'),
    ('Register',        'register'),
    ('Length',          'length'),
    ('Is Single Word',  'is_single_word'),
    ('First Attested',  'first_attested'),
    ('Family',          'family'),
    ('Wordle Eligible', 'wordle_eligible'),
    ('Puzzle Difficulty', 'puzzle_difficulty'),
    ('Ship',            'ship'),
    ('Reviewer 1',      'reviewer_1'),
    ('Reviewer 2',      'reviewer_2'),
    ('Date Approved',   'date_approved'),
    ('Source',          'source'),
    ('License',        'license'),
    ('Notes',          'notes'),
]


def _format_value(val):
    """Format a JSON value for the spreadsheet."""
    if val is None:
        return ''
    if isinstance(val, list):
        return ' | '.join(str(v) for v in val)
    if isinstance(val, bool):
        return 'TRUE' if val else 'FALSE'
    return val


def main():
    if not os.path.exists(JSON_PATH):
        print(f'ERROR: {JSON_PATH} not found. Run migrate_to_json.py first.')
        sys.exit(1)

    with open(JSON_PATH, 'r', encoding='utf-8') as f:
        doc = json.load(f)

    words = doc['words']
    print(f'Read {len(words)} words from JSON (schema {doc["schema_version"]}).')

    wb = openpyxl.Workbook()

    # Dictionary sheet
    ws = wb.active
    ws.title = 'Dictionary'

    # Headers
    for col_idx, (header, _) in enumerate(COLUMNS, 1):
        ws.cell(row=1, column=col_idx, value=header)

    # Data rows
    for row_idx, word in enumerate(words, 2):
        for col_idx, (_, key) in enumerate(COLUMNS, 1):
            ws.cell(row=row_idx, column=col_idx, value=_format_value(word.get(key)))

    # README sheet
    readme = wb.create_sheet('README')
    readme.cell(row=1, column=1,
                value='Generated from vulgus_lexicon.json \u2014 do not edit this file directly')

    wb.save(OUT_PATH)
    print(f'Wrote {OUT_PATH} ({len(words)} words)')


if __name__ == '__main__':
    main()
